language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=3.0.8
  - DJANGO_VERSION=dev

matrix:
  allow_failures:
    - env: DJANGO_VERSION=dev

install:
    - pip install requirements.txt
