# Generated by Django 3.0.8 on 2020-11-19 17:15

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_interactionstatistic_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptativeWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='BadgeWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='ChallengeWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='DevelopmentToolWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='EasterEggWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='GiftOpenerWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='GiftWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='KnowledgeShareWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
                ('messages', jsonfield.fields.JSONField(default=dict)),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='LeaderboardWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='LevelWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='LotteryWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='PointWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='SocialNetworkWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='SocialStatusWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
        migrations.CreateModel(
            name='UnlockableWidget',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
            ],
            bases=('api.gmechanic',),
        ),
    ]
