# Generated by Django 3.0.8 on 2020-11-19 17:15

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_adaptativewidget_badgewidget_challengewidget_developmenttoolwidget_eastereggwidget_giftopenerwidget_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmechanic',
            name='mechanic_type',
            field=enumfields.fields.EnumField(default='Unknown', enum=api.models.GMechanic.MechanicType, max_length=12),
        ),
    ]
