# Generated by Django 3.0.8 on 2020-11-30 20:53

import api.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20201119_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMechanicList',
            fields=[
                ('gmechanic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.GMechanic')),
                ('mechanic', enumfields.fields.EnumField(default='badges', enum=api.models.GMechanicList.Mechanics, max_length=17)),
            ],
            bases=('api.gmechanic',),
        ),
    ]
