# Generated by Django 3.0.8 on 2020-12-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_gmechaniclist'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='reward_by',
            field=models.CharField(default='score', max_length=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reward_value',
            field=models.FloatField(default=10),
        ),
    ]
